# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

source 'https://github.com/appodeal/CocoaPods.git'
source 'https://cdn.cocoapods.org/'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'apntaloreact' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'apntaloreactTests' do
    inherit! :complete
    # Pods for testing
  end

  # Appodeal 3.5.0 SDK with confirmed working adapters
  pod 'Appodeal', '3.5.0', :source => 'https://github.com/appodeal/CocoaPods.git'
  pod 'APDBidMachineAdapter', '3.5.0.0', :source => 'https://github.com/appodeal/CocoaPods.git'     # BidMachine - Appodeal's own demand source
  pod 'APDAppLovinAdapter', '3.5.0.0', :source => 'https://github.com/appodeal/CocoaPods.git'       # AppLovin MAX mediation
  pod 'APDVungleAdapter', '3.5.0.0', :source => 'https://github.com/appodeal/CocoaPods.git'         # Vungle/Liftoff adapter  
  pod 'APDInMobiAdapter', '3.5.0.0', :source => 'https://github.com/appodeal/CocoaPods.git'         # InMobi adapter
  pod 'APDMyTargetAdapter', '3.5.0.0', :source => 'https://github.com/appodeal/CocoaPods.git'       # MyTarget adapter
  pod 'APDMintegralAdapter', '3.5.0.0', :source => 'https://github.com/appodeal/CocoaPods.git'      # Mintegral adapter
  pod 'APDAmazonAdapter', '3.5.0.0', :source => 'https://github.com/appodeal/CocoaPods.git'         # Amazon Publisher Services
  pod 'APDSmaatoAdapter', '3.5.0.0', :source => 'https://github.com/appodeal/CocoaPods.git'         # Smaato adapter
  pod 'APDYandexAdapter', '3.5.0.0', :source => 'https://github.com/appodeal/CocoaPods.git'         # Yandex adapter
  pod 'APDPangleAdapter', '3.5.0.0', :source => 'https://github.com/appodeal/CocoaPods.git'         # Pangle (TikTok) adapter
  pod 'APDBigoAdsAdapter', '3.5.0.0', :source => 'https://github.com/appodeal/CocoaPods.git'        # BigoAds adapter
  pod 'APDDTExchangeAdapter', '3.5.0.0', :source => 'https://github.com/appodeal/CocoaPods.git'     # DTExchange adapter
  pod 'APDBidonAdapter', '3.5.0.0', :source => 'https://github.com/appodeal/CocoaPods.git'          # Bidon mediation platform
  pod 'APDAdjustAdapter', '3.5.0.0', :source => 'https://github.com/appodeal/CocoaPods.git'
  pod 'APDAppLovinMAXAdapter', '3.5.0.0', :source => 'https://github.com/appodeal/CocoaPods.git'
  pod 'APDAppsFlyerAdapter', '3.5.0.0', :source => 'https://github.com/appodeal/CocoaPods.git'
  pod 'APDFacebookAdapter', '3.5.0.0', :source => 'https://github.com/appodeal/CocoaPods.git'
  pod 'APDIABAdapter', '3.5.0.0', :source => 'https://github.com/appodeal/CocoaPods.git'
  pod 'APDIronSourceAdapter', '3.5.0.0', :source => 'https://github.com/appodeal/CocoaPods.git'
  pod 'StackConsentManager', '2.0.10', :source => 'https://github.com/appodeal/CocoaPods.git'
  pod 'APDLevelPlayAdapter', '3.5.0.0', :source => 'https://github.com/appodeal/CocoaPods.git'
  pod 'APDMetaAudienceNetworkAdapter', '3.5.0.0', :source => 'https://github.com/appodeal/CocoaPods.git'
#   pod 'APDSentryAdapter', '3.5.0.0', :source => 'https://github.com/appodeal/CocoaPods.git'
#   pod 'Sentry', '~> 8.0'

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
pod "glog", :podspec => "../node_modules/react-native/third-party-podspecs/glog.podspec", :modular_headers => false
